version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: "echo 'db.runCommand({ ping: 1 })' | mongo localhost:27017/admin -u root -p example --quiet"
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo-data:
