version: '3.8'

services:
  monitor-service:
    build:
      context: ./monitor-service
      dockerfile: Dockerfile
    image: monitor-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/articles

  mongo:
    build:
      context: ./mongo-service
      dockerfile: Dockerfile
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
